### ISSUE TITLE
{BUG}: HTTP POST not being called.

### ISSUE THREAD

**Issue by AbhijithGanesh** [guptasajal411/easy-sync#7]
When I try to delete the text I enter, there is no successful change at all

**Comment by guptasajal411** [comment]
I tweaked around and rewrote the code, and it works now!
Main commit: [#29](https://github.com/guptasajal411/easy-sync/commit/feaa8053e45ef639533a562251f857997cbdd284)
Result:
![image](https://user-images.githubusercontent.com/70312106/134634076-3277516a-d326-4f13-ae41-2a67dc46e268.png)

**Comment by AbhijithGanesh** [comment]
Great, let me check.

**Comment by guptasajal411** [comment]
Sure, please raise another issue if you notice any bug or improvement 💥
